name: asp-ideas
channels:
  - conda-forge
  - potassco
  - anaconda
dependencies:
  - python>=3.6,<4
  - clingo=5.5
  - python-clingox=1.0
  - clorm=1.3
  - networkx=2.7
  - pydot=1.4
  - jupyter=1.0
  - jupyterlab=3.2
  - ipysheet=0.5
  - pip
  - pip:
      - xclingo
