name: asp-ideas
channels:
  - potassco
  - conda-forge
dependencies:
  - python>=3.6,<4
  - clingo=5.5
  - networkx=2.7
  - pydot=1.4
  - jupyter=1.0
  - jupyterlab=3.2
  - ipysheet=0.5
  - pip
  - pip:
      - xclingo
