name: asp-ideas
channels:
  - conda-forge
  - potassco
  - anaconda
dependencies:
  - python>=3.6,<4
  - clingo>=5.5,<6
  - python-clingox>=1.1,<2
  - more-itertools>=8.13,<9
  - pymunk>=6.2,<7
  - clorm>=1.3,<2
  - clingraph>=1.0,<2
  - telingo>=2.1,<3
  - networkx>=2.7,<3
  - shapely>=1.8,<2
  - descartes>=1.1,<2
  - pydot>=1.4,<2
  - notebook>=6.4,<7
  - jupyterlab>=3.4,<4
  - ipysheet>=0.5,<1
  - pip
  - pip:
      - xclingo
      - polygon3>=3.0.9.1,<4
      - pyclipper>=1.3.0,<2
